[tool.poetry]
name = "oanda-fxdata-etl"
version = "0.1.0"
description = "ETL scripts which manipulate Oanda FX tick data and allow for ingestion to a timescale db"
authors = ["Juraj Zachar <juraj.zachar@gmail.com>"]
license = "GNU GPL"
packages = [
    { include = "oanda-fxdata-etl" }
]

[tool.poetry.dependencies]
python = "^3.10"
psycopg2-binary = "^2.9"
fastapi = "^0.104"

[tool.poetry.dev-dependencies]
pytest = "^7"
pytest-cov = "^4"
mockito = "^1.4"
testcontainers = {version=">=3.7", extras=["postgres"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"