[tool.poetry]
name = "oanda-fxdata-etl"
version = "0.1.0"
description = "ETL scripts which manipulate Oanda FX tick data and allow for ingestion to a timescale db"
authors = ["Juraj Zachar <juraj.zachar@gmail.com>"]
license = "GNU GPL"
packages = [
    { include = "oanda-fxdata-etl" }
]

[tool.poetry.dependencies]
python = "^3.8"
wheel = "^0.36"
Flask = "^2.0"
six = "^1.16"
Jinja2 = "^3.0"

[tool.poetry.dev-dependencies]
mockito = "^1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"